version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE_NAME}
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - AMAZON__USERNAME=youremail@gmail.com
      - AMAZON__PASSWORD=encrypted_amazon_password_using_utlis_encrypt_method 
    networks:
      - app-network
  ui:
    image: ${FRONTEND_IMAGE_NAME}
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - REVIEWS_PER_PAGE=8
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
