version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE_NAME}
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - AMAZON__USERNAME=shrikrishna.kadam4@gmail.com
      - AMAZON_PASSWORD=gAAAAABno2ly0_Z1pPK_TxguCLEvsfmCoKQvPiILtqiqX6Fk5x06mpLSQ_XTz2KvJniqkyWIr07kn5A9uPRjrQUd6a82WWbz9w==
    networks:
      - app-network
  ui:
    image: ${FRONTEND_IMAGE_NAME}
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - REVIEWS_PER_PAGE=8
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
